In [1]:
import numpy as np

arr = np.arange(1, 11)

print("Array:", arr)
print("Type:", type(arr))
print("Shape:", arr.shape)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Type: <class 'numpy.ndarray'>
Shape: (10,)


In [7]:
zeros = np.zeros((3, 3))
ones = np.ones((3, 3))

print("Zeros Matrix:")
print(zeros)

print("Ones Matrix:")
print(ones)

Zeros Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
arr = np.linspace(0, 1, 10)

print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [4]:
arr = np.random.randint(1, 101, 10)
print("Original Array:", arr)
sorted_arr = np.sort(arr)
print("Sorted Array:", sorted_arr)

Original Array: [95 47 64 26  5 31 61 59 62 36]
Sorted Array: [ 5 26 31 36 47 59 61 62 64 95]


In [5]:
arr = np.array([12, 45, 23, 56, 78, 10])
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

Minimum: 10
Maximum: 78
Mean: 37.333333333333336
Standard Deviation: 24.682427397284535


In [6]:
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
arr = np.array([1, 2, 3, 4, 5])
print("Original:", arr)
print("Add 5:", arr + 5)
print("Multiply by 2:", arr * 2)

Original: [1 2 3 4 5]
Add 5: [ 6  7  8  9 10]
Multiply by 2: [ 2  4  6  8 10]


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Dot Product:", np.dot(a, b))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Dot Product: 32


In [10]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("First 3:", arr[:3])
print("Last 3:", arr[-3:])
print("Middle Elements:", arr[3:5])

First 3: [10 20 30]
Last 3: [60 70 80]
Middle Elements: [40 50]


In [11]:
import pandas as pd
data = {
    'Name': ['A', 'B', 'C'],
    'Age': [20, 25, 30]
}
df = pd.DataFrame(data)
print(df)

  Name  Age
0    A   20
1    B   25
2    C   30


NameError: name 'pokemon_complete' is not defined