In [1]:
import numpy as np
#create a numpy array with values[1,2,3,4,5]
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
#create an array of all zeros with size 5 
arr2=np.zeros(5)
print(arr2)

[0. 0. 0. 0. 0.]


In [4]:
#create an array of all ones with size 10
arr3=np.ones(10)
print(arr3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
#create an array from 10 to 50
arr4=np.arange(10,51)
print(arr4)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [7]:
#create an array of even numbers from 2 to 20
arr5=np.arange(2,21,2)
print(arr5)

[ 2  4  6  8 10 12 14 16 18 20]


In [8]:
#generate 5 random numbers between 0 and 1
arr6=np.random.rand(5)
print(arr6)

[0.68234703 0.53861835 0.71361303 0.6001269  0.09190574]


In [9]:
#find the datatype of an array
print(arr1.dtype)

int32


In [10]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
#add two arrays
print(a+b)

[ 7  9 11 13 15]


In [11]:
#subtract two arrays
print(a-b)

[-5 -5 -5 -5 -5]


In [12]:
#multiply two arrays
print(a*b)

[ 6 14 24 36 50]


In [13]:
#divide two arrays
print(a/b)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [14]:
#find square of each element
print(a**2)

[ 1  4  9 16 25]


In [15]:
#find square root of each element
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [16]:
#find sum of all elements
print(np.sum(a))

15


In [17]:
#slice first 5 elements
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[:5])

[1 2 3 4 5]


In [18]:
#slice alternate elements
print(arr[::2])

[1 3 5 7 9]


In [19]:
#reverse an array using slicing
print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1]


In [20]:
#extract middle 3 values
print(arr[4:7])

[5 6 7]
